// FuelSavings
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

// SimpleCounter
export const SIMPLECOUNTER_INCREASE = 'SIMPLECOUNTER_INCREASE';
export const SIMPLECOUNTER_DECREASE = 'SIMPLECOUNTER_DECREASE';

// Bottles
export const ADD_BOTTLE = 'ADD_BOTTLE';
export const EDIT_BOTTLE = 'EDIT_BOTTLE';
export const DELETE_BOTTLE = 'DELETE_BOTTLE';

// Collection-bottles api test
export const FETCHCOLLECTION_REQUEST = 'FETCHCOLLECTION_REQUEST';
export const FETCHCOLLECTION_SUCCESS = 'FETCHCOLLECTION_SUCCESS';
export const FETCHCOLLECTION_FAILURE = 'FETCHCOLLECTION_FAILURE';

export const FETCHCOLLECTIONS_REQUEST = 'FETCHCOLLECTIONS_REQUEST';
export const FETCHCOLLECTIONS_SUCCESS = 'FETCHCOLLECTIONS_SUCCESS';
export const FETCHCOLLECTIONS_FAILURE = 'FETCHCOLLECTIONS_FAILURE';
