// FuelSavings
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

// SimpleCounter
export const SIMPLECOUNTER_INCREASE = 'SIMPLECOUNTER_INCREASE';
export const SIMPLECOUNTER_DECREASE = 'SIMPLECOUNTER_DECREASE';
