import merge from 'lodash/merge'


const initialState = { bottles: {}, collections: {} };

// Updates an entity cache in response to any action with response.entities.
// This property is generated by normalizr in the RSAA's Success-FSA of the RSAA (redux-api-middleware).
// As seen in redux-api-middleware and the Redux real-world example.

export default function entities(state = initialState, action) {
  if (action.payload && action.payload.entities) {
    // Do a 'deep' merge with all entities we already know
    return merge({}, state, action.payload.entities)
    // todo: Think about what to do with deleted items.
  }

  return state
}
